#!/usr/bin/env python3
r"""
latex_semantic_scan.py

Companion to latex_var_scan.py. Where that script finds *what symbols exist*,
this one drafts *what each symbol means*, by pattern-matching declaration
sentences ("$G$ is a group", "$H$ is a subgroup of $G$") near math spans.

Pipeline:
    1. extract   -> scan a page, produce a DRAFT symbol->meaning table (YAML)
    2. (human edits the draft - fixes misparses, fills gaps, deletes noise)
    3. check     -> re-scan the page, compare against the human-approved
                    table, flag:
                      - REDEFINITION: same symbol, conflicting role/meaning
                      - DRIFT: new declaration not yet in the approved table
                      - POSSIBLE_ALIAS (soft): different symbol, near-identical
                        meaning string (maybe intentional, maybe a slip)

Patterns are configurable (see DEFAULT_PATTERNS / --patterns-file) so this
isn't tied to group theory specifically - swap in a template file for
whatever area of math a given wiki section covers.

No LaTeX installation or external dependencies required.
"""

import re
import sys
import json
import argparse
import difflib
from pathlib import Path

try:
    import yaml
    HAVE_YAML = True
except ImportError:
    HAVE_YAML = False


# --------------------------------------------------------------------------
# 1. Declaration templates (configurable)
#
# Each pattern is applied to a *desugared* sentence where every math span
# has been replaced by a placeholder token \x01<content>\x02, so the regex
# only has to deal with the surrounding English, not LaTeX escaping.
#
# Capture groups:
#   sym   - the symbol being declared (required)
#   role  - short role label, e.g. "group", "subgroup", "homomorphism"
#   rel   - the related symbol, if any (e.g. the G in "subgroup of G")
# --------------------------------------------------------------------------

# Prepositions that connect a symbol to its "container"/context in a
# declaration sentence ("subgroup OF G", "map FROM G", "series IN G",
# "element FROM S", "generated BY S"). Configurable so a project can add
# domain-specific ones without touching the regexes below.
# Prepositions that connect a symbol to its "container"/context in a
# declaration sentence ("subgroup OF G", "map FROM G", "series IN G",
# "element FROM S"). Configurable so a project can add domain-specific
# ones without touching the regexes below. Deliberately excludes "by":
# in math prose "by" is ambiguous - sometimes a clean single-argument
# connector ("normalized by G") but often the second argument of a
# two-object construction ("quotient of G by N", "wreath product of A
# by B") where treating it like "of"/"from" would misparse the relation
# the same way "with" did (see SECOND_ARG_CONNECTORS below). Safer to
# not match "by" here at all than to sometimes match it wrong.
REL_PREPOSITIONS = ["of", "from", "in", "over", "on", "into", "onto"]

# Prepositions that, when they appear where a "with"-style second-argument
# connector would, signal a two-argument construction ("wreath product OF
# A WITH B") rather than the "descriptor + target" idiom ("subgroup OF a
# finite group G"). Matches on these are skipped rather than mis-parsed -
# see the "also_declares_rel" skip logic in extract_declarations.
SECOND_ARG_CONNECTORS = ["with", "and", "by"]

_REL_PREP_ALT = "|".join(REL_PREPOSITIONS)
_SECOND_ARG_RE = re.compile(
    r"\b(?:" + "|".join(SECOND_ARG_CONNECTORS) + r")\b", re.IGNORECASE
)

# A "binding" INTRODUCES a symbol ("Let L be the center of K", "define
# C_K(g) to be...", "we denote by K^* the multiplicative group"). A
# "property assertion" states something TRUE about an already-introduced
# symbol ("L is a field", "L is an additive subgroup of K"). Only bindings
# can conflict with each other - a proof legitimately derives many
# simultaneously-true properties of the same object, and treating each new
# property as a redefinition of the last is the single largest source of
# false positives on real proof pages.
BINDING_MARKERS_RE = re.compile(
    r"^\s*(?:let\b|define\b|set\b|put\b|we\s+denote\b|denote\b|write\b|"
    r"suppose\b|assume\b|consider\b|take\b|for\s+an?\b)",
    re.IGNORECASE,
)

# Conclusion markers: an equation appearing in a sentence like "we conclude
# d = 1" or "thus K = L" is a DERIVED RESULT, not a definition of d or K.
# Without this, a proof's own conclusion registers as a redefinition of
# the symbol it constrains.
CONCLUSION_MARKERS_RE = re.compile(
    r"\b(?:conclude|thus|hence|therefore|so\s+that|forces?|must\s+have|"
    r"it\s+follows|we\s+get|we\s+obtain|implies|show(?:s|ed)?\s+that|"
    r"this\s+gives|equality\s+holds)\b",
    re.IGNORECASE,
)


def classify_declaration_kind(sentence, clause=None):
    """Return 'binding' or 'assertion' for a declaration found in this
    sentence. Bindings are what REDEFINITION compares; assertions merely
    accumulate."""
    probe = clause if clause is not None else sentence
    if BINDING_MARKERS_RE.match(probe.strip()):
        return "binding"
    return "assertion"

DEFAULT_PATTERNS = [
    # "G is a group" / "let G be a group" / "let G be the group"
    {
        "regex": r"(?:let|suppose)?\s*SYM\((?P<sym>[^)]+)\)\s+(?:is|be)\s+(?:an?|the)\s+(?P<role>[\w -]+?)"
                 r"(?=[.,;]|\s+(?:" + _REL_PREP_ALT + r"|that|which|among)\b|$)",
        "template": "{sym} is a {role}",
    },
    # "H is a subgroup of G" / "the map from G onto H" / "N is a subgroup in G"
    {
        "regex": r"SYM\((?P<sym>[^)]+)\)\s+(?:is|be)\s+(?:an?|the)\s+(?P<role>[\w -]+?)"
                 r"\s+(?P<prep>" + _REL_PREP_ALT + r")\s+SYM\((?P<rel>[^)]+)\)",
        "template": "{sym} is a {role} {prep} {rel}",
    },
    # "H is a subgroup of a finite group G" - the target carries its OWN
    # descriptor inline, which simultaneously declares that target too.
    # This is a very common idiom ("...of a finite group G", "...of an
    # abelian group A", "...in a finite group G") and without it, G/A
    # look permanently undeclared even when the page does introduce them,
    # just not via a standalone "Let G be..." sentence.
    {
        "regex": r"SYM\((?P<sym>[^)]+)\)\s+(?:is|be)\s+(?:an?|the)\s+(?P<role>[\w -]+?)"
                 r"\s+(?P<prep>" + _REL_PREP_ALT + r")\s+(?:an?|the)\s+(?P<rel_role>[\w -]+?)\s+SYM\((?P<rel>[^)]+)\)",
        "template": "{sym} is a {role} {prep} {rel}",
        "also_declares_rel": True,
    },
    # "we denote by K^* the multiplicative group of nonzero elements of K"
    # / "denote by L the center". Inverted word order: the symbol comes
    # BEFORE its descriptor, so the ordinary "X is a Y" patterns miss it
    # entirely and X looks permanently undeclared.
    {
        "regex": r"(?:we\s+)?denote\s+by\s+SYM\((?P<sym>[^)]+)\)\s+(?:an?|the)\s+(?P<role>[\w -]+?)(?=[.,;]|\s+(?:"
                 + _REL_PREP_ALT + r"|that|which)\b|$)",
        "template": "{sym} is a {role}",
    },
    # "N is normal in G"
    {
        "regex": r"SYM\((?P<sym>[^)]+)\)\s+is\s+(?P<role>normal|central|characteristic|abelian|solvable|nilpotent)\s+in\s+SYM\((?P<rel>[^)]+)\)",
        "template": "{sym} is {role} in {rel}",
    },
    # "phi: G -> H is a homomorphism"
    {
        "regex": r"SYM\((?P<sym>[^)]+)\)\s*:\s*SYM\([^)]+\)\s*\\?to\s*SYM\([^)]+\)\s+is\s+an?\s+(?P<role>[\w -]+)",
        "template": "{sym} is a {role} (map)",
    },
    # "x in G" as a bare membership declaration (weaker signal, lower confidence)
    {
        "regex": r"SYM\((?P<sym>[^)]+)\)\s*\\in\s*SYM\((?P<rel>[^)]+)\)",
        "template": "{sym} is an element of {rel}",
        "confidence": "low",
    },
]

# Patterns applied directly to a single math span's raw content (not to
# surrounding prose) - for definitional equations like "B = \mathbb{F}_p[H]"
# or "A = \mathbb{F}_p[G] \rtimes G", where the whole declaration lives
# inside one math span with no English words at all.
EQUATION_PATTERNS = [
    {
        # LHS must be a "simple" symbol (letters/digits/sub/superscript,
        # no top-level '=' of its own) so we don't misfire on e.g. "x^2 = y^2".
        "regex": r"^\s*(?P<sym>[A-Za-z](?:_\{[^{}]*\}|_[A-Za-z0-9]|\^\{[^{}]*\}|\^[A-Za-z0-9])*)\s*=\s*(?P<rhs>.+)$",
        "template": "{sym} is defined as {rhs}",
        "confidence": "medium",
    },
]


def load_patterns(path):
    if path is None:
        return DEFAULT_PATTERNS
    data = json.loads(Path(path).read_text())
    return data


# --------------------------------------------------------------------------
# 2. Sentence splitting + math-span placeholder substitution
# --------------------------------------------------------------------------

MATH_SPAN_RE = re.compile(
    r"(?<!\\)\$\$(.+?)(?<!\\)\$\$"
    r"|(?<!\\)\$(.+?)(?<!\\)\$"
    r"|\\\((.+?)\\\)"
    # <math>...</math> matched case-insensitively: real pages contain
    # typos like "<matH>" / "</matH>", and a case-sensitive pattern
    # silently SKIPS those spans rather than reporting them, which is
    # the worst failure mode for a checker. See find_malformed_math_tags()
    # for the companion check that reports them as an issue.
    r"|<[Mm][Aa][Tt][Hh]>(.+?)</[Mm][Aa][Tt][Hh]>",
    re.DOTALL,
)


def find_malformed_math_tags(text):
    """Report <math> tags whose case is non-canonical (e.g. '<matH>') or
    that are unbalanced. Returns list of (line_no, message). Purely
    deterministic - exactly the class of error this tool exists to catch."""
    issues = []
    for m in re.finditer(r"</?[Mm][Aa][Tt][Hh]>", text):
        tag = m.group(0)
        canonical = tag.lower()
        if tag != canonical:
            line = text.count("\n", 0, m.start()) + 1
            issues.append((line, f"non-canonical math tag {tag!r} (should be {canonical!r})"))

    opens = len(re.findall(r"<[Mm][Aa][Tt][Hh]>", text))
    closes = len(re.findall(r"</[Mm][Aa][Tt][Hh]>", text))
    if opens != closes:
        issues.append((0, f"unbalanced math tags: {opens} opening, {closes} closing"))
    return issues

SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+(?=[A-Z\\$])")


def strip_wiki_markup(text):
    """Remove MediaWiki structural markup that isn't prose, so it can't
    break mid-sentence pattern matching. Applied BEFORE math-span
    desugaring, so it must not touch <math>...</math> contents."""
    # Protect math spans first so markup-stripping regexes can't reach inside them.
    protected = []

    def stash(m):
        protected.append(m.group(0))
        return f"\x00{len(protected) - 1}\x00"

    text = MATH_SPAN_RE.sub(stash, text)

    # [[fact about::X;| ]][[X]]  or  [[uses::X]]: -> drop annotation links entirely
    text = re.sub(r"\[\[[a-zA-Z ]+::[^\]]*\]\]", "", text)
    # [[Page name|Display text]] -> Display text ; [[Page name]] -> Page name
    text = re.sub(r"\[\[([^\]|]+)\|([^\]]*)\]\]", lambda m: m.group(2) or m.group(1), text)
    text = re.sub(r"\[\[([^\]]+)\]\]", r"\1", text)
    # '' italics / ''' bold -> strip markers, keep text
    text = re.sub(r"'{2,3}", "", text)
    # {{template}} -> drop entirely (e.g. {{tabular proof format}})
    text = re.sub(r"\{\{[^{}]*\}\}", "", text)
    # <toggledisplay>...</toggledisplay> and similar inline wiki HTML ->
    # keep the CONTENTS (it's real explanatory prose, often where the
    # actual declarations live) but drop the tags themselves.
    text = re.sub(r"</?toggledisplay>", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"</?(?:small|sup|sub|br|ref)\s*/?>", " ", text, flags=re.IGNORECASE)
    # Table markup: {| ... |} wrapper lines, |- row separators, ! header
    # cells. Cell separators (|| and leading |) become sentence-ending
    # periods so adjacent cells don't run together into one bogus
    # "sentence" spanning several columns.
    text = re.sub(r"^\s*\{\|.*$", "", text, flags=re.MULTILINE)   # table open
    text = re.sub(r"^\s*\|\}.*$", "", text, flags=re.MULTILINE)   # table close
    text = re.sub(r"^\s*\|-.*$", "", text, flags=re.MULTILINE)    # row separator
    text = re.sub(r"^\s*!.*$", "", text, flags=re.MULTILINE)      # header row
    text = re.sub(r"\|\|", ". ", text)                            # cell separator
    text = re.sub(r"^[ \t]*\|\s*", "", text, flags=re.MULTILINE)  # leading cell pipe
    # == Headers == -> drop the line entirely (not prose)
    text = re.sub(r"^\s*=+.*=+\s*$", "", text, flags=re.MULTILINE)
    # leading list markers (* # :) -> drop, keep rest of line
    text = re.sub(r"^[ \t]*[*#:]+\s*", "", text, flags=re.MULTILINE)

    # Restore math spans
    def restore(m):
        return protected[int(m.group(1))]

    text = re.sub(r"\x00(\d+)\x00", restore, text)
    return text


def desugar(text):
    """Replace math spans with SYM(<content>) placeholders; return
    (desugared_text, list_of_original_spans_in_order)."""
    spans = []

    def repl(m):
        content = next(g for g in m.groups() if g is not None)
        spans.append(content.strip())
        return f"SYM({content.strip()})"

    return MATH_SPAN_RE.sub(repl, text), spans


HEADER_RE = re.compile(r"^(=+)\s*(.*?)\s*=+\s*$")


def split_into_scopes(text):
    """Split raw page text into (scope_path, segment_text) chunks using
    MediaWiki '== Header ==' lines to build a nesting path, e.g. a
    subsection under Proof gets scope_path ('Proof', 'Example 1').

    Table rows ('|-' separators) additionally open a nested scope, since
    in the tabular-proof format each numbered step is a self-contained
    unit: symbols are routinely re-described per step ("L is a field",
    "L is the center of K") and comparing across steps produces noise
    the same way comparing across sibling ===Example=== sections did.

    This runs BEFORE strip_wiki_markup/desugar - it only understands
    header and row syntax, nothing else.
    """
    segments = []
    stack = []  # list of (level, title)
    current_lines = []
    row_counter = [0]
    in_row = [False]

    def flush():
        if any(l.strip() for l in current_lines):
            path = tuple(title for _, title in stack)
            if in_row[0]:
                path = path + (f"row {row_counter[0]}",)
            segments.append((path, "\n".join(current_lines)))
        current_lines.clear()

    for line in text.split("\n"):
        stripped = line.strip()
        m = HEADER_RE.match(stripped)
        if m:
            flush()
            in_row[0] = False
            row_counter[0] = 0
            level = len(m.group(1))
            title = m.group(2).strip()
            while stack and stack[-1][0] >= level:
                stack.pop()
            stack.append((level, title))
        elif stripped.startswith("|-"):
            # Row separator: close the previous row's scope, open the next.
            flush()
            row_counter[0] += 1
            in_row[0] = True
        elif stripped.startswith("|}"):
            # Table closed - back to plain section scope.
            flush()
            in_row[0] = False
            row_counter[0] = 0
        else:
            current_lines.append(line)
    flush()
    return segments


def scopes_related(a, b):
    """True if scope path `a` and `b` are the same, or one is an ancestor
    of the other (nested), so a declaration in one is visible from the
    other. False for siblings/cousins - e.g. two independent '===Example'
    subsections under the same '==Proof==' are NOT related, since each
    is its own self-contained construction and reusing a variable name
    across them is normal, not a redefinition."""
    n = min(len(a), len(b))
    return a[:n] == b[:n]


def _is_row(component):
    return component.startswith("row ")


def scope_visible_from(declared_scope, use_scope):
    """Visibility is WIDER than relatedness. Two rows of one tabular proof
    are siblings for redefinition purposes (each step restates properties
    of the same objects, and comparing across steps is noise) - but a proof
    is sequential, so a symbol introduced in step 4 IS legitimately in
    scope at step 9. Treat earlier rows of the same table as visible;
    otherwise fall back to ordinary relatedness."""
    if (declared_scope and use_scope
            and _is_row(declared_scope[-1]) and _is_row(use_scope[-1])
            and declared_scope[:-1] == use_scope[:-1]):
        try:
            return int(declared_scope[-1][4:]) <= int(use_scope[-1][4:])
        except ValueError:
            return True
    return scopes_related(declared_scope, use_scope)


def scope_label(scope_path):
    return " > ".join(scope_path) if scope_path else "(page top)"


def normalize_symbol(raw):
    """Strip outer whitespace and common no-op wrapping so 'G' and ' G '
    and '{G}' collapse to the same key. Deliberately shallow - reuses the
    same notion of 'atom' as latex_var_scan.py would, but kept standalone
    here to avoid a hard dependency between the two scripts."""
    s = raw.strip()
    s = re.sub(r"^\{(.*)\}$", r"\1", s)
    return s


# --------------------------------------------------------------------------
# 3. Extraction
# --------------------------------------------------------------------------

CLAUSE_SPLIT_RE = re.compile(r"\s+and\s+(?=SYM\()")


def split_clauses(sentence):
    """Split a sentence into clauses on ' and ' when the next clause starts
    with a math-span placeholder - e.g. 'A is a group and A is a subgroup
    of B' becomes two clauses. This deliberately only splits before SYM(
    (i.e. before a new subject), so 'the join of H1 and H2' or similar
    phrases inside a single clause are left alone."""
    return CLAUSE_SPLIT_RE.split(sentence)


def extract_declarations(text, patterns, equation_patterns=None):
    """Return list of dicts: {sym, role, rel, meaning, sentence, confidence,
    scope}. `scope` is a tuple of enclosing MediaWiki header titles, e.g.
    ('Proof', 'Example 1'), or () for content before any header."""
    results = []

    for scope_path, seg_text in split_into_scopes(text):
        seg_text = strip_wiki_markup(seg_text)
        desugared, spans = desugar(seg_text)
        sentences = SENTENCE_SPLIT_RE.split(desugared)

        for sent in sentences:
          for clause in split_clauses(sent):
            sent_matches = []
            for pat in patterns:
                # Patterns are written with a literal "SYM(" for readability;
                # turn that into the escaped "SYM\(" the regex engine needs.
                working = pat["regex"].replace("SYM(", r"SYM\(")
                # finditer (not search): a single clause can still carry
                # more than one pattern match (e.g. bare is-a + is-a-of
                # both matching overlapping text) - collect all, dedup below.
                for m in re.finditer(working, clause, flags=re.IGNORECASE):
                    gd = m.groupdict()
                    sym = normalize_symbol(gd.get("sym", ""))
                    role = (gd.get("role") or "").strip()
                    rel = normalize_symbol(gd.get("rel", "")) if gd.get("rel") else None
                    prep = (gd.get("prep") or "of").strip()
                    meaning = pat["template"].format(sym=sym, role=role, rel=rel, prep=prep)

                    # "of A with B" (e.g. "wreath product of the group of
                    # prime order with W") is a two-argument construction,
                    # NOT the "prep a <descriptor> X" idiom this pattern is
                    # meant for (e.g. "subgroup of a finite group G"). If
                    # the captured rel_role swallowed a trailing connector
                    # word (with/and/by/...), that descriptor is unreliable
                    # - but the primary fact "sym relates to rel" (role and
                    # rel come from separate, unaffected capture groups) is
                    # still fine and worth keeping at reduced confidence:
                    # dropping it entirely would make W (the referent)
                    # invisible to UNDECLARED_REFERENT rather than correctly
                    # flagged as "referenced but never itself declared".
                    descriptor_unreliable = pat.get("also_declares_rel") and _SECOND_ARG_RE.search(gd.get("rel_role") or "")
                    if descriptor_unreliable:
                        confidence = "low"
                    else:
                        confidence = pat.get("confidence", "high")

                    sent_matches.append({
                        "sym": sym,
                        "role": role,
                        "rel": rel,
                        "meaning": meaning,
                        "sentence": sent.strip(),
                        "confidence": confidence,
                        "scope": scope_path,
                        "kind": classify_declaration_kind(sent, clause),
                        "span": (m.start(), m.end()),
                    })
                    # Some patterns (e.g. "...of a finite group G") declare
                    # BOTH symbols in one match: the primary sym, and the
                    # relation target via its own inline descriptor. Emit a
                    # second declaration for the latter, anchored to the
                    # same span so dedup treats it as part of the same
                    # match - but only when the descriptor itself is
                    # trustworthy (see descriptor_unreliable above).
                    if pat.get("also_declares_rel") and gd.get("rel_role") and not descriptor_unreliable:
                        rel_role = gd["rel_role"].strip()
                        sent_matches.append({
                            "sym": rel,
                            "role": rel_role,
                            "rel": None,
                            "meaning": f"{rel} is a {rel_role}",
                            "sentence": sent.strip(),
                            "confidence": pat.get("confidence", "high"),
                            "scope": scope_path,
                            # An inline descriptor ("...of a finite group G")
                            # introduces G, so it counts as a binding.
                            "kind": "binding",
                            "span": (m.start(), m.end()),
                        })

            # Dedup within this clause: when two matches overlap and share
            # the same symbol, keep only the wider (more specific) one,
            # e.g. "is-a-of" over bare "is-a" for the same span, since the
            # narrower one is almost always a partial submatch of the same
            # underlying declaration, not a second distinct one.
            sent_matches.sort(key=lambda r: -(r["span"][1] - r["span"][0]))
            kept = []
            for r in sent_matches:
                s0, e0 = r["span"]
                overlaps_kept_wider = any(
                    r["sym"] == k["sym"] and not (e0 <= k["span"][0] or s0 >= k["span"][1])
                    for k in kept
                )
                if not overlaps_kept_wider:
                    kept.append(r)
            for r in kept:
                del r["span"]
            results.extend(kept)

        # Second pass: definitional equations living entirely inside one
        # math span, e.g. "B = \mathbb{F}_p[H]" - these have no surrounding
        # English for the sentence-level patterns to anchor on.
        #
        # An equation in a CONCLUSION sentence ("thus d = 1", "we conclude
        # K = L") is a derived result, not a definition: treating it as one
        # makes a proof's own conclusion look like a redefinition of the
        # symbol it constrains. We locate each span's enclosing sentence to
        # decide. Likewise a bare-numeral RHS ("d = 1") is essentially never
        # a definition in running proof text.
        for content in spans:
            enclosing = ""
            marker = f"SYM({content.strip()})"
            for s in sentences:
                if marker in s:
                    enclosing = s
                    break

            if CONCLUSION_MARKERS_RE.search(enclosing):
                continue

            for pat in (equation_patterns or EQUATION_PATTERNS):
                m = re.match(pat["regex"], content.strip())
                if not m:
                    continue
                gd = m.groupdict()
                sym = normalize_symbol(gd.get("sym", ""))
                rhs = (gd.get("rhs") or "").strip()
                if re.fullmatch(r"-?\d+", rhs):
                    break  # "d = 1" - a constraint/result, not a definition
                meaning = pat["template"].format(sym=sym, role="", rel=None, rhs=rhs)
                results.append({
                    "sym": sym,
                    "role": "",
                    "rel": None,
                    "meaning": meaning,
                    "sentence": enclosing.strip() or f"${content.strip()}$",
                    "confidence": pat.get("confidence", "medium"),
                    "scope": scope_path,
                    "kind": "binding",
                })
                break

    return results


# --------------------------------------------------------------------------
# 4. Draft table generation (extract mode)
# --------------------------------------------------------------------------

def build_draft_table(declarations):
    """Group by symbol; a symbol may have multiple declarations if reused
    (that's exactly what we want the human to review). Each entry keeps
    its scope path so re-use across independent sections (e.g. two
    sibling ===Example=== subsections) doesn't get treated the same as
    re-use within one section."""
    table = {}
    for d in declarations:
        table.setdefault(d["sym"], []).append({
            "meaning": d["meaning"],
            "confidence": d["confidence"],
            "source_sentence": d["sentence"],
            "scope": list(d["scope"]),
            "kind": d.get("kind", "binding"),
        })
    return table


def write_table(table, path):
    if path.endswith((".yml", ".yaml")) and HAVE_YAML:
        Path(path).write_text(yaml.dump(table, sort_keys=True, allow_unicode=True))
    else:
        Path(path).write_text(json.dumps(table, indent=2, ensure_ascii=False))


def read_table(path):
    text = Path(path).read_text()
    if path.endswith((".yml", ".yaml")) and HAVE_YAML:
        return yaml.safe_load(text) or {}
    return json.loads(text)


# --------------------------------------------------------------------------
# 5. Consistency checking (check mode)
# --------------------------------------------------------------------------

def similar(a, b, threshold=0.82):
    return difflib.SequenceMatcher(None, a.lower(), b.lower()).ratio() >= threshold


def dedupe_declarations(declarations):
    """Collapse declarations that are identical in (sym, meaning, scope).
    The same math span or sentence often recurs across table cells, and
    re-reporting each copy inflates both the draft table and the issue
    list without adding information. Keeps first occurrence order."""
    seen = set()
    out = []
    for d in declarations:
        key = (d["sym"], d["meaning"], d["scope"])
        if key in seen:
            continue
        seen.add(key)
        out.append(d)
    return out


def check_consistency(declarations, approved_table):
    """Return list of (severity, message) tuples.

    Scope-aware: a symbol re-used with a different meaning is only flagged
    as REDEFINITION if the two declarations occur in *related* scopes
    (same section or table row, or one nested inside the other). Sibling
    scopes - two independent '===Example...===' subsections, or two steps
    of a tabular proof - are NOT compared against each other, since reuse
    there is normal, not a slip.

    Kind-aware: only 'binding' declarations ("Let L be the center of K")
    are compared for REDEFINITION. 'assertion' declarations ("L is a
    field", "L is an additive subgroup of K") state properties that are
    simultaneously true, so they accumulate rather than conflict.

    Each declaration is compared against the MOST RECENT related binding
    only, not every prior one - pairwise comparison turns n declarations
    of one symbol into O(n^2) messages saying substantially the same thing.
    """
    declarations = dedupe_declarations(declarations)

    issues = []
    last_meaning = {}  # sym -> (scope, meaning) of most recent declaration of any kind
    declared_syms = []  # list of (scope, sym) for every symbol declared so far, in order

    # Symbols declared together in the same sentence (e.g. "N is a subgroup
    # of a group M" declares N and M in one match) count as simultaneous,
    # not sequential - without this, whichever of the pair happens to be
    # processed first would wrongly see the other as "not yet declared".
    same_sentence_syms = {}
    for d in declarations:
        key = (d["scope"], d["sentence"])
        same_sentence_syms.setdefault(key, set()).add(d["sym"])

    for d in declarations:
        sym, meaning, scope = d["sym"], d["meaning"], d["scope"]

        # UNDECLARED_REFERENT: this declaration explains sym in terms of
        # another symbol ("B is a subgroup of C"), but that other symbol
        # has never itself been declared anywhere in a related scope -
        # it's only ever appeared as someone else's "of X" target, never
        # as a subject in its own right. Checked against declarations seen
        # so far (textual order) PLUS anything declared in this same
        # sentence (simultaneous declarations, see same_sentence_syms above).
        if d.get("rel") and d["rel"] != sym:
            rel_declared = any(
                s == d["rel"] and scope_visible_from(rscope, scope)
                for rscope, s in declared_syms
            )
            if not rel_declared:
                rel_declared = d["rel"] in same_sentence_syms.get((scope, d["sentence"]), set())
            if not rel_declared:
                issues.append((
                    "UNDECLARED_REFERENT",
                    f"'{d['rel']}' is used to describe '{sym}' (\"{meaning}\") "
                    f"[{scope_label(scope)}] but '{d['rel']}' itself is never "
                    f"declared -- (\"{d['sentence'][:70]}\")",
                ))

        # SELF_REFERENCE: symbol declared in terms of itself, e.g.
        # "A is a subgroup of A". Always worth a human look regardless
        # of scope - this is a deterministic, high-confidence catch.
        if d.get("rel") and d["rel"] == sym:
            issues.append((
                "SELF_REFERENCE",
                f"'{sym}' is declared in terms of itself: \"{meaning}\" "
                f"[{scope_label(scope)}] -- (\"{d['sentence'][:70]}\")",
            ))

        # REDEFINITION: fires when a symbol is re-BOUND to a meaningfully
        # different meaning within a related scope. The *current*
        # declaration must be a binding (property assertions accumulate and
        # never conflict), but it is compared against the most recent prior
        # meaning of either kind - re-binding a symbol that already had an
        # established meaning is exactly the error worth catching, whether
        # that meaning came from an earlier binding or an assertion.
        if d.get("kind", "binding") == "binding":
            prior = last_meaning.get(sym)
            if prior is not None:
                prior_scope, prior_meaning = prior
                if scopes_related(prior_scope, scope) and not similar(prior_meaning, meaning):
                    issues.append((
                        "REDEFINITION",
                        f"'{sym}' previously meant \"{prior_meaning}\" "
                        f"[{scope_label(prior_scope)}], now re-bound as \"{meaning}\" "
                        f"[{scope_label(scope)}] -- (\"{d['sentence'][:70]}\")",
                    ))
        last_meaning[sym] = (scope, meaning)

        # DRIFT: not present in the human-approved table at all, or present
        # only under an unrelated scope.
        approved = approved_table.get(sym)
        if approved is None:
            issues.append((
                "DRIFT",
                f"'{sym}' declared as \"{meaning}\" [{scope_label(scope)}] "
                f"but not in approved table -- (\"{d['sentence'][:70]}\")",
            ))
        else:
            relevant = [
                a for a in approved
                if scopes_related(tuple(a.get("scope", [])), scope)
            ]
            candidates = relevant or approved  # fall back to all if scope info missing/unrelated
            approved_meanings = [a["meaning"] for a in candidates]
            if not any(similar(meaning, am) for am in approved_meanings):
                issues.append((
                    "DRIFT",
                    f"'{sym}' now means \"{meaning}\" [{scope_label(scope)}] but "
                    f"approved table (same-scope entries) says {approved_meanings} "
                    f"-- (\"{d['sentence'][:70]}\")",
                ))

        declared_syms.append((scope, sym))

    # POSSIBLE_ALIAS (soft): different symbols, near-identical meaning text,
    # restricted to related scopes - otherwise every page-wide reuse of
    # "is a subgroup of" phrasing floods the output with noise.
    items = [(d["sym"], d["meaning"], d["scope"]) for d in declarations]
    for i in range(len(items)):
        for j in range(i + 1, len(items)):
            sym_a, mean_a, scope_a = items[i]
            sym_b, mean_b, scope_b = items[j]
            if (sym_a != sym_b
                    and scopes_related(scope_a, scope_b)
                    and similar(mean_a, mean_b, threshold=0.9)):
                issues.append((
                    "POSSIBLE_ALIAS",
                    f"'{sym_a}' [{scope_label(scope_a)}] and '{sym_b}' "
                    f"[{scope_label(scope_b)}] both mean \"{mean_a}\" -- "
                    f"confirm this is intentional (e.g. two distinct subgroups)",
                ))

    return issues


# --------------------------------------------------------------------------
# 6. CLI
# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_extract = sub.add_parser("extract", help="Draft a symbol->meaning table from a page")
    p_extract.add_argument("file")
    p_extract.add_argument("--out", required=True, help="Output path for draft table (.json or .yaml)")
    p_extract.add_argument("--patterns-file", default=None)

    p_check = sub.add_parser("check", help="Check a page against a human-approved table")
    p_check.add_argument("file")
    p_check.add_argument("--approved", required=True, help="Path to human-approved table")
    p_check.add_argument("--patterns-file", default=None)

    args = ap.parse_args()
    patterns = load_patterns(args.patterns_file)
    text = Path(args.file).read_text()
    declarations = extract_declarations(text, patterns)

    if args.cmd == "extract":
        for line_no, msg in find_malformed_math_tags(text):
            loc = f"line {line_no}" if line_no else "file"
            print(f"[MALFORMED_MATH_TAG] {loc}: {msg}")
        declarations = dedupe_declarations(declarations)
        table = build_draft_table(declarations)
        write_table(table, args.out)
        print(f"Extracted {len(declarations)} declarations, {len(table)} distinct symbols.")
        print(f"Draft table written to {args.out} -- please review before using as 'approved'.")

    elif args.cmd == "check":
        approved = read_table(args.approved)
        issues = [
            ("MALFORMED_MATH_TAG", (f"line {ln}: " if ln else "") + msg)
            for ln, msg in find_malformed_math_tags(text)
        ]
        issues += check_consistency(declarations, approved)
        if not issues:
            print("Clean: no redefinitions, drift, or possible aliases detected.")
        for severity, msg in issues:
            print(f"[{severity}] {msg}")
        print(f"\n--- summary: {len(issues)} issue(s) across {len(declarations)} declaration(s) ---")


if __name__ == "__main__":
    main()
