#!/usr/bin/env python3
r"""
latex_semantic_scan.py

Companion to latex_var_scan.py. Where that script finds *what symbols exist*,
this one drafts *what each symbol means*, by pattern-matching declaration
sentences ("$G$ is a group", "$H$ is a subgroup of $G$") near math spans.

Pipeline:
    1. extract   -> scan a page, produce a DRAFT symbol->meaning table (YAML)
    2. (human edits the draft - fixes misparses, fills gaps, deletes noise)
    3. check     -> re-scan the page, compare against the human-approved
                    table, flag:
                      - REDEFINITION: same symbol, conflicting role/meaning
                      - DRIFT: new declaration not yet in the approved table
                      - POSSIBLE_ALIAS (soft): different symbol, near-identical
                        meaning string (maybe intentional, maybe a slip)

Patterns are configurable (see DEFAULT_PATTERNS / --patterns-file) so this
isn't tied to group theory specifically - swap in a template file for
whatever area of math a given wiki section covers.

No LaTeX installation or external dependencies required.
"""

import re
import sys
import json
import argparse
import difflib
from pathlib import Path

try:
    import yaml
    HAVE_YAML = True
except ImportError:
    HAVE_YAML = False


# --------------------------------------------------------------------------
# 1. Declaration templates (configurable)
#
# Each pattern is applied to a *desugared* sentence where every math span
# has been replaced by a placeholder token \x01<content>\x02, so the regex
# only has to deal with the surrounding English, not LaTeX escaping.
#
# Capture groups:
#   sym   - the symbol being declared (required)
#   role  - short role label, e.g. "group", "subgroup", "homomorphism"
#   rel   - the related symbol, if any (e.g. the G in "subgroup of G")
# --------------------------------------------------------------------------

# Prepositions that connect a symbol to its "container"/context in a
# declaration sentence ("subgroup OF G", "map FROM G", "series IN G",
# "element FROM S", "generated BY S"). Configurable so a project can add
# domain-specific ones without touching the regexes below.
# Prepositions that connect a symbol to its "container"/context in a
# declaration sentence ("subgroup OF G", "map FROM G", "series IN G",
# "element FROM S"). Configurable so a project can add domain-specific
# ones without touching the regexes below. Deliberately excludes "by":
# in math prose "by" is ambiguous - sometimes a clean single-argument
# connector ("normalized by G") but often the second argument of a
# two-object construction ("quotient of G by N", "wreath product of A
# by B") where treating it like "of"/"from" would misparse the relation
# the same way "with" did (see SECOND_ARG_CONNECTORS below). Safer to
# not match "by" here at all than to sometimes match it wrong.
REL_PREPOSITIONS = ["of", "from", "in", "over", "on", "into", "onto"]

# Prepositions that, when they appear where a "with"-style second-argument
# connector would, signal a two-argument construction ("wreath product OF
# A WITH B") rather than the "descriptor + target" idiom ("subgroup OF a
# finite group G"). Matches on these are skipped rather than mis-parsed -
# see the "also_declares_rel" skip logic in extract_declarations.
SECOND_ARG_CONNECTORS = ["with", "and", "by"]

_REL_PREP_ALT = "|".join(REL_PREPOSITIONS)
_SECOND_ARG_RE = re.compile(
    r"\b(?:" + "|".join(SECOND_ARG_CONNECTORS) + r")\b", re.IGNORECASE
)

# A "binding" INTRODUCES a symbol ("Let L be the center of K", "define
# C_K(g) to be...", "we denote by K^* the multiplicative group"). A
# "property assertion" states something TRUE about an already-introduced
# symbol ("L is a field", "L is an additive subgroup of K"). Only bindings
# can conflict with each other - a proof legitimately derives many
# simultaneously-true properties of the same object, and treating each new
# property as a redefinition of the last is the single largest source of
# false positives on real proof pages.
# Restatement markers: a sentence that re-expresses something already
# stated ("Equivalently, A = F_p[G] x G ...", "In symbols, H = <H_1,H_2>",
# "In other words, K is the largest normal subgroup...") describes the SAME
# object a second way. Treating those as fresh bindings makes every
# "here it is in symbols" sentence look like a redefinition of the thing it
# is restating - a very common shape in mathematical writing.
RESTATEMENT_MARKERS_RE = re.compile(
    r"^\s*(?:equivalently|in\s+symbols|in\s+other\s+words|that\s+is|namely|"
    r"i\.e\.|explicitly|more\s+precisely|put\s+differently|"
    r"stated\s+differently|alternatively)\b",
    re.IGNORECASE,
)

BINDING_MARKERS_RE = re.compile(
    r"^\s*(?:let\b|define\b|set\b|put\b|we\s+denote\b|denote\b|write\b|"
    r"suppose\b|assume\b|consider\b|take\b|for\s+an?\b)",
    re.IGNORECASE,
)

# Conclusion markers: an equation appearing in a sentence like "we conclude
# d = 1" or "thus K = L" is a DERIVED RESULT, not a definition of d or K.
# Without this, a proof's own conclusion registers as a redefinition of
# the symbol it constrains.
CONCLUSION_MARKERS_RE = re.compile(
    r"\b(?:conclude|thus|hence|therefore|so\s+that|forces?|must\s+have|"
    r"it\s+follows|we\s+get|we\s+obtain|implies|show(?:s|ed)?\s+that|"
    r"this\s+gives|equality\s+holds)\b",
    re.IGNORECASE,
)


GOAL_CONTEXT_RE = re.compile(
    r"^\s*(?:to\s+prove|we\s+must\s+show|we\s+want\s+to\s+show|claim)\b",
    re.IGNORECASE,
)

EXISTENTIAL_RE = re.compile(r"\bthere\s+exists?\b", re.IGNORECASE)


def classify_declaration_kind(sentence, clause=None):
    """Return 'binding' or 'assertion' for a declaration found in this
    sentence. Bindings are what REDEFINITION compares; assertions merely
    accumulate."""
    probe = clause if clause is not None else sentence
    # A restatement re-expresses an existing object, so it can never be a
    # fresh binding no matter what verb it uses. Checked against the whole
    # sentence, since the marker leads the sentence while the declaration
    # may sit in a later clause.
    if RESTATEMENT_MARKERS_RE.match(sentence.strip()):
        return "assertion"
    # A goal ("To prove: there exists a group K such that ...") states what
    # is to be established, and an existential names a witness that a later
    # step will construct. Neither binds the symbol, so a subsequent "Let K
    # be ..." is instantiation, not redefinition.
    if GOAL_CONTEXT_RE.match(sentence.strip()) or EXISTENTIAL_RE.search(sentence):
        return "assertion"
    if BINDING_MARKERS_RE.match(probe.strip()):
        return "binding"
    return "assertion"

# Verbless declarations. Groupprops proof pages introduce symbols with no
# verb at all - "Given: A group G, a normal subgroup H of G", "The
# following are equivalent for a subgroup H of a group G". Every
# "X is a Y" pattern misses these, so G and K end up looking permanently
# undeclared on essentially every proof page.
#
# Applied ONLY inside a declaration context (below), because the bare
# shape "a <descriptor> SYM(x)" is far too common in ordinary prose
# ("the direct factors of V", "a homomorphic image of V") to trust on
# its own.
DECLARATION_CONTEXT_RE = re.compile(
    r"^\s*(?:given|to\s+prove|suppose|assume|consider|let|"
    r"the\s+following\s+are\s+equivalent|we\s+are\s+given)\b",
    re.IGNORECASE,
)

VERBLESS_PATTERNS = [
    # "a normal subgroup H of G" / "a group K containing G"
    {
        "regex": r"(?:[,;:]|\bfor\b|\bgiven\b|\bare\b)\s+(?:an?|the)\s+(?P<role>[\w -]+?)\s+SYM\((?P<sym>[^)]+)\)"
                 r"\s+(?P<prep>" + _REL_PREP_ALT + r")\s+(?:an?|the)\s+(?P<rel_role>[\w -]+?)\s+SYM\((?P<rel>[^)]+)\)",
        "template": "{sym} is a {role} {prep} {rel}",
        # "a subgroup H of a group G" introduces G too.
        "also_declares_rel": True,
    },
    # same, but the target has no descriptor: "a normal subgroup H of G"
    {
        "regex": r"(?:[,;:]|\bfor\b|\bgiven\b|\bare\b)\s+(?:an?|the)\s+(?P<role>[\w -]+?)\s+SYM\((?P<sym>[^)]+)\)"
                 r"\s+(?P<prep>" + _REL_PREP_ALT + r")\s+SYM\((?P<rel>[^)]+)\)",
        "template": "{sym} is a {role} {prep} {rel}",
    },
    # "a division ring K of finite size" - the trailing qualifier is prose
    # with no symbol in it, so the relational patterns above don't apply,
    # but the symbol IS being declared.
    {
        "regex": r"(?:[,;:]|\bfor\b|\bgiven\b|\bare\b|\bexists\b)\s+(?:an?|the)\s+(?P<role>[\w -]+?)\s+SYM\((?P<sym>[^)]+)\)"
                 r"\s+(?:" + _REL_PREP_ALT + r")\s+(?P<qualifier>[\w -]+?)(?=\s*[,.;:]|$)",
        "template": "{sym} is a {role}",
    },
    # "A group G" / "a subgroup H" with no trailing relation
    {
        "regex": r"(?:[,;:]|\bfor\b|\bgiven\b|\bare\b|\bexists\b)\s+(?:an?|the)\s+(?P<role>[\w -]+?)\s+SYM\((?P<sym>[^)]+)\)"
                 r"(?=\s*[,.;:]|\s+(?:such|that|which|containing|with)\b|$)",
        "template": "{sym} is a {role}",
    },
]

DEFAULT_PATTERNS = [
    # "G is a group" / "let G be a group" / "let G be the group"
    {
        "regex": r"(?:let|suppose)?\s*SYM\((?P<sym>[^)]+)\)\s+(?:is|be)\s+(?:an?|the)\s+(?P<role>[\w -]+?)"
                 r"(?=[.,;]|\s+(?:" + _REL_PREP_ALT + r"|that|which|among)\b|$)",
        "template": "{sym} is a {role}",
    },
    # "H is a subgroup of G" / "the map from G onto H" / "N is a subgroup in G"
    {
        "regex": r"SYM\((?P<sym>[^)]+)\)\s+(?:is|be)\s+(?:an?|the)\s+(?P<role>[\w -]+?)"
                 r"\s+(?P<prep>" + _REL_PREP_ALT + r")\s+SYM\((?P<rel>[^)]+)\)",
        "template": "{sym} is a {role} {prep} {rel}",
    },
    # "H is a subgroup of a finite group G" - the target carries its OWN
    # descriptor inline, which simultaneously declares that target too.
    # This is a very common idiom ("...of a finite group G", "...of an
    # abelian group A", "...in a finite group G") and without it, G/A
    # look permanently undeclared even when the page does introduce them,
    # just not via a standalone "Let G be..." sentence.
    {
        "regex": r"SYM\((?P<sym>[^)]+)\)\s+(?:is|be)\s+(?:an?|the)\s+(?P<role>[\w -]+?)"
                 r"\s+(?P<prep>" + _REL_PREP_ALT + r")\s+(?:an?|the)\s+(?P<rel_role>[\w -]+?)\s+SYM\((?P<rel>[^)]+)\)",
        "template": "{sym} is a {role} {prep} {rel}",
        "also_declares_rel": True,
    },
    # "we denote by K^* the multiplicative group of nonzero elements of K"
    # / "denote by L the center". Inverted word order: the symbol comes
    # BEFORE its descriptor, so the ordinary "X is a Y" patterns miss it
    # entirely and X looks permanently undeclared.
    {
        "regex": r"(?:we\s+)?denote\s+by\s+SYM\((?P<sym>[^)]+)\)\s+(?:an?|the)\s+(?P<role>[\w -]+?)(?=[.,;]|\s+(?:"
                 + _REL_PREP_ALT + r"|that|which)\b|$)",
        "template": "{sym} is a {role}",
    },
    # Appositive subject: "the multiplicative group L^* of nonzero elements
    # of L is the center of K^*". The true subject is L^* (appositive to the
    # head noun "multiplicative group"), but a naive left-to-right scan finds
    # the NEAREST symbol before "is" - here L, the object of "of ... of" -
    # and misattributes the whole predicate to it. This pattern anchors on
    # the head noun instead, and allows intervening prepositional phrases
    # (the "mid" group) between the subject symbol and its verb.
    # It also declares the subject's own role ("L^* is a multiplicative
    # group") via also_declares_subj_role.
    {
        "regex": r"(?:the|an?)\s+(?P<subj_role>[\w -]+?)\s+SYM\((?P<sym>[^)]+)\)"
                 # The modifier tail may be set off by commas or wrapped in
                 # parentheses - which is exactly the punctuation the
                 # AMBIGUOUS_ATTACHMENT advisory asks authors to add, so it
                 # must keep parsing (and stop warning) once they do.
                 r"(?P<mid>(?:\s*[,(]?\s*(?:" + _REL_PREP_ALT + r")\s+"
                 r"(?:(?!\bis\b|\bbe\b)[\w -]|SYM\([^)]*\))+?)+[,)]?)"
                 r"\s+(?:is|be)\s+(?:an?|the)\s+(?P<role>[\w -]+?)"
                 r"\s+(?P<prep>" + _REL_PREP_ALT + r")\s+SYM\((?P<rel>[^)]+)\)",
        "template": "{sym} is a {role} {prep} {rel}",
        "also_declares_subj_role": True,
    },
    # "Let G denote a finite group" / "K^* denotes the multiplicative group".
    # The verb is "denote", not "is/be", so the ordinary patterns miss it
    # and the symbol looks undeclared.
    {
        "regex": r"(?:let\s+)?SYM\((?P<sym>[^)]+)\)\s+denotes?\s+(?:an?|the)\s+(?P<role>[\w -]+?)"
                 r"(?=[.,;]|\s+(?:" + _REL_PREP_ALT + r"|that|which)\b|$)",
        "template": "{sym} is a {role}",
    },
    # "Let the prime be p" / "let the base field be L" - inverted binding,
    # descriptor first and symbol last.
    {
        "regex": r"let\s+(?:the|an?)\s+(?P<role>[\w -]+?)\s+be\s+SYM\((?P<sym>[^)]+)\)",
        "template": "{sym} is a {role}",
    },
    # "G is the group GA^+(1,\R)" - appositive NAMING: the descriptor is
    # followed directly by a symbol that names the subject, with no
    # preposition between. Distinct from "H is a subgroup of G", where the
    # trailing symbol is a relation target rather than a name.
    {
        "regex": r"SYM\((?P<sym>[^)]+)\)\s+(?:is|be)\s+(?:an?|the)\s+(?P<role>[\w -]+?)"
                 # One level of nested parens allowed: math content like
                 # "GA^+(1,\R)" contains them, and the usual [^)]+ delimiter
                 # would stop at the first inner ')'.
                 r"\s+SYM\((?P<name>(?:[^()]|\([^()]*\))+)\)(?=\s*[,.;:]|$)",
        "template": "{sym} is a {role}",
    },
    # "N is normal in G"
    {
        "regex": r"SYM\((?P<sym>[^)]+)\)\s+is\s+(?P<role>normal|central|characteristic|abelian|solvable|nilpotent)\s+in\s+SYM\((?P<rel>[^)]+)\)",
        "template": "{sym} is {role} in {rel}",
    },
    # "phi: G -> H is a homomorphism"
    {
        "regex": r"SYM\((?P<sym>[^)]+)\)\s*:\s*SYM\([^)]+\)\s*\\?to\s*SYM\([^)]+\)\s+is\s+an?\s+(?P<role>[\w -]+)",
        "template": "{sym} is a {role} (map)",
    },
    # "x in G" as a bare membership declaration (weaker signal, lower confidence)
    {
        "regex": r"SYM\((?P<sym>[^)]+)\)\s*\\in\s*SYM\((?P<rel>[^)]+)\)",
        "template": "{sym} is an element of {rel}",
        "confidence": "low",
    },
]

# Patterns applied directly to a single math span's raw content (not to
# surrounding prose) - for definitional equations like "B = \mathbb{F}_p[H]"
# or "A = \mathbb{F}_p[G] \rtimes G", where the whole declaration lives
# inside one math span with no English words at all.
EQUATION_PATTERNS = [
    {
        # LHS must be a "simple" symbol (letters/digits/sub/superscript,
        # no top-level '=' of its own) so we don't misfire on e.g. "x^2 = y^2".
        "regex": r"^\s*(?P<sym>[A-Za-z](?:_\{[^{}]*\}|_[A-Za-z0-9]|\^\{[^{}]*\}|\^[A-Za-z0-9])*)\s*=\s*(?P<rhs>.+)$",
        "template": "{sym} is defined as {rhs}",
        "confidence": "medium",
    },
]


def load_patterns(path):
    if path is None:
        return DEFAULT_PATTERNS
    data = json.loads(Path(path).read_text())
    return data


# --------------------------------------------------------------------------
# 2. Sentence splitting + math-span placeholder substitution
# --------------------------------------------------------------------------

MATH_SPAN_RE = re.compile(
    r"(?<!\\)\$\$(.+?)(?<!\\)\$\$"
    r"|(?<!\\)\$(.+?)(?<!\\)\$"
    r"|\\\((.+?)\\\)"
    # <math>...</math> matched case-insensitively: real pages contain
    # typos like "<matH>" / "</matH>", and a case-sensitive pattern
    # silently SKIPS those spans rather than reporting them, which is
    # the worst failure mode for a checker. See find_malformed_math_tags()
    # for the companion check that reports them as an issue.
    r"|<[Mm][Aa][Tt][Hh]>(.+?)</[Mm][Aa][Tt][Hh]>",
    re.DOTALL,
)


def find_malformed_math_tags(text):
    """Report structural problems with <math> tags. Returns a list of
    (severity, line_no, message).

    Two severities, because they matter very differently:

      MATH_TAG_CASE      - cosmetic only. MediaWiki matches the tag
                           case-insensitively, so '<matH>' renders exactly
                           like '<math>'. Worth tidying when you're already
                           editing, but it is invisible to readers and must
                           not gate a pipeline.

      MALFORMED_MATH_TAG - genuinely broken: empty, unbalanced, or crossed
                           delimiters. These change what renders AND corrupt
                           span detection downstream, turning prose into
                           phantom variables.
    """
    issues = []
    for m in re.finditer(r"</?[Mm][Aa][Tt][Hh]>", text):
        tag = m.group(0)
        canonical = tag.lower()
        if tag != canonical:
            line = text.count("\n", 0, m.start()) + 1
            issues.append(("MATH_TAG_CASE", line,
                           f"non-canonical math tag {tag!r} (should be "
                           f"{canonical!r}) - cosmetic, does not affect rendering"))

    # Empty spans: <math></math> contains nothing, so MATH_SPAN_RE (which
    # requires at least one character) skips past it and instead matches
    # from this opening tag to the NEXT closing tag - swallowing the prose
    # in between and turning ordinary letters into phantom variables.
    for m in re.finditer(r"<[Mm][Aa][Tt][Hh]>\s*</[Mm][Aa][Tt][Hh]>", text):
        line = text.count("\n", 0, m.start()) + 1
        issues.append(("MALFORMED_MATH_TAG", line,
                       "empty math span (<math></math>) - will corrupt "
                       "span detection for the rest of the line"))

    # Swallowed prose: a matched span whose contents still contain a math
    # tag means the delimiters are crossed somewhere (unclosed tag, stray
    # tag). The parse downstream is meaningless until it's fixed.
    for m in MATH_SPAN_RE.finditer(text):
        content = next((g for g in m.groups() if g is not None), "")
        if re.search(r"</?[Mm][Aa][Tt][Hh]>", content):
            line = text.count("\n", 0, m.start()) + 1
            issues.append(("MALFORMED_MATH_TAG", line,
                           "math span contains a nested/stray math tag - "
                           f"delimiters are crossed: {content.strip()[:50]!r}"))

    opens = len(re.findall(r"<[Mm][Aa][Tt][Hh]>", text))
    closes = len(re.findall(r"</[Mm][Aa][Tt][Hh]>", text))
    if opens != closes:
        issues.append(("MALFORMED_MATH_TAG", 0,
                       f"unbalanced math tags: {opens} opening, {closes} closing"))
    return issues

SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+(?=[A-Z\\$])")


def strip_wiki_markup(text):
    """Remove MediaWiki structural markup that isn't prose, so it can't
    break mid-sentence pattern matching. Applied BEFORE math-span
    desugaring, so it must not touch <math>...</math> contents."""
    # Protect math spans first so markup-stripping regexes can't reach inside them.
    protected = []

    def stash(m):
        protected.append(m.group(0))
        return f"\x00{len(protected) - 1}\x00"

    text = MATH_SPAN_RE.sub(stash, text)

    # [[fact about::X;| ]][[X]]  or  [[uses::X]]: -> drop annotation links entirely
    text = re.sub(r"\[\[[a-zA-Z ]+::[^\]]*\]\]", "", text)
    # [[Page name|Display text]] -> Display text ; [[Page name]] -> Page name
    text = re.sub(r"\[\[([^\]|]+)\|([^\]]*)\]\]", lambda m: m.group(2) or m.group(1), text)
    text = re.sub(r"\[\[([^\]]+)\]\]", r"\1", text)
    # '' italics / ''' bold -> strip markers, keep text
    text = re.sub(r"'{2,3}", "", text)
    # <pre>...</pre> is verbatim code, not prose. Left in, GAP snippets get
    # spliced into declaration sentences and quoted back as evidence.
    text = re.sub(r"<pre>.*?</pre>", " ", text, flags=re.DOTALL | re.IGNORECASE)
    # {{template}} -> drop entirely (e.g. {{tabular proof format}})
    text = re.sub(r"\{\{[^{}]*\}\}", "", text)
    # <toggledisplay>...</toggledisplay> and similar inline wiki HTML ->
    # keep the CONTENTS (it's real explanatory prose, often where the
    # actual declarations live) but drop the tags themselves.
    text = re.sub(r"</?toggledisplay>", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"</?(?:small|sup|sub|br|ref)\s*/?>", " ", text, flags=re.IGNORECASE)
    # Table markup: {| ... |} wrapper lines, |- row separators, ! header
    # cells. Cell separators (|| and leading |) become sentence-ending
    # periods so adjacent cells don't run together into one bogus
    # "sentence" spanning several columns.
    text = re.sub(r"^\s*\{\|.*$", "", text, flags=re.MULTILINE)   # table open
    text = re.sub(r"^\s*\|\}.*$", "", text, flags=re.MULTILINE)   # table close
    text = re.sub(r"^\s*\|-.*$", "", text, flags=re.MULTILINE)    # row separator
    text = re.sub(r"^\s*!.*$", "", text, flags=re.MULTILINE)      # header row
    text = re.sub(r"\|\|", ". ", text)                            # cell separator
    text = re.sub(r"^[ \t]*\|\s*", "", text, flags=re.MULTILINE)  # leading cell pipe
    # == Headers == -> drop the line entirely (not prose)
    text = re.sub(r"^\s*=+.*=+\s*$", "", text, flags=re.MULTILINE)
    # leading list markers (* # :) -> drop, keep rest of line
    text = re.sub(r"^[ \t]*[*#:]+\s*", "", text, flags=re.MULTILINE)

    # Restore math spans
    def restore(m):
        return protected[int(m.group(1))]

    text = re.sub(r"\x00(\d+)\x00", restore, text)
    return text


def desugar(text):
    """Replace math spans with SYM(<content>) placeholders; return
    (desugared_text, list_of_original_spans_in_order)."""
    spans = []

    def repl(m):
        content = next(g for g in m.groups() if g is not None)
        spans.append(content.strip())
        return f"SYM({content.strip()})"

    return MATH_SPAN_RE.sub(repl, text), spans


HEADER_RE = re.compile(r"^(=+)\s*(.*?)\s*=+\s*$")


def split_into_scopes(text):
    """Split raw page text into (scope_path, segment_text) chunks using
    MediaWiki '== Header ==' lines to build a nesting path, e.g. a
    subsection under Proof gets scope_path ('Proof', 'Example 1').

    Table rows ('|-' separators) additionally open a nested scope, since
    in the tabular-proof format each numbered step is a self-contained
    unit: symbols are routinely re-described per step ("L is a field",
    "L is the center of K") and comparing across steps produces noise
    the same way comparing across sibling ===Example=== sections did.

    This runs BEFORE strip_wiki_markup/desugar - it only understands
    header and row syntax, nothing else.
    """
    segments = []
    stack = []  # list of (level, title)
    current_lines = []
    row_counter = [0]
    in_row = [False]

    def flush():
        if any(l.strip() for l in current_lines):
            path = tuple(title for _, title in stack)
            if in_row[0]:
                path = path + (f"row {row_counter[0]}",)
            segments.append((path, "\n".join(current_lines)))
        current_lines.clear()

    for line in text.split("\n"):
        stripped = line.strip()
        m = HEADER_RE.match(stripped)
        if m:
            flush()
            in_row[0] = False
            row_counter[0] = 0
            level = len(m.group(1))
            title = m.group(2).strip()
            while stack and stack[-1][0] >= level:
                stack.pop()
            stack.append((level, title))
        elif stripped.startswith("|-"):
            # Row separator: close the previous row's scope, open the next.
            flush()
            row_counter[0] += 1
            in_row[0] = True
        elif stripped.startswith("|}"):
            # Table closed - back to plain section scope.
            flush()
            in_row[0] = False
            row_counter[0] = 0
        else:
            current_lines.append(line)
    flush()
    return segments


def scopes_related(a, b):
    """True if scope path `a` and `b` are the same, or one is an ancestor
    of the other (nested), so a declaration in one is visible from the
    other. False for siblings/cousins - e.g. two independent '===Example'
    subsections under the same '==Proof==' are NOT related, since each
    is its own self-contained construction and reusing a variable name
    across them is normal, not a redefinition."""
    n = min(len(a), len(b))
    return a[:n] == b[:n]


def _is_row(component):
    return component.startswith("row ")


def scope_visible_from(declared_scope, use_scope):
    """Visibility is WIDER than relatedness. Two rows of one tabular proof
    are siblings for redefinition purposes (each step restates properties
    of the same objects, and comparing across steps is noise) - but a proof
    is sequential, so a symbol introduced in step 4 IS legitimately in
    scope at step 9. Treat earlier rows of the same table as visible;
    otherwise fall back to ordinary relatedness."""
    if (declared_scope and use_scope
            and _is_row(declared_scope[-1]) and _is_row(use_scope[-1])
            and declared_scope[:-1] == use_scope[:-1]):
        try:
            return int(declared_scope[-1][4:]) <= int(use_scope[-1][4:])
        except ValueError:
            return True
    return scopes_related(declared_scope, use_scope)


def scope_label(scope_path):
    return " > ".join(scope_path) if scope_path else "(page top)"


def normalize_symbol(raw):
    """Strip outer whitespace and common no-op wrapping so 'G' and ' G '
    and '{G}' collapse to the same key. Deliberately shallow - reuses the
    same notion of 'atom' as latex_var_scan.py would, but kept standalone
    here to avoid a hard dependency between the two scripts."""
    s = raw.strip()
    s = re.sub(r"^\{(.*)\}$", r"\1", s)
    return s


# --------------------------------------------------------------------------
# 3. Extraction
# --------------------------------------------------------------------------

CLAUSE_SPLIT_RE = re.compile(r"\s+and\s+(?=SYM\()")


def split_clauses(sentence):
    """Split a sentence into clauses on ' and ' when the next clause starts
    with a math-span placeholder - e.g. 'A is a group and A is a subgroup
    of B' becomes two clauses. This deliberately only splits before SYM(
    (i.e. before a new subject), so 'the join of H1 and H2' or similar
    phrases inside a single clause are left alone."""
    return CLAUSE_SPLIT_RE.split(sentence)


def _find_antecedent(sentences, idx, sym):
    """Nearest preceding sentence (within this scope segment) that mentions
    `sym` inside a math placeholder. Returns the sentence text, or None."""
    needle = re.compile(r"SYM\([^)]*\b" + re.escape(sym) + r"\b[^)]*\)")
    for k in range(idx - 1, -1, -1):
        if needle.search(sentences[k]):
            return sentences[k].strip()
    return None


def extract_declarations(text, patterns, equation_patterns=None):
    """Return list of dicts: {sym, role, rel, meaning, sentence, confidence,
    scope}. `scope` is a tuple of enclosing MediaWiki header titles, e.g.
    ('Proof', 'Example 1'), or () for content before any header."""
    results = []

    for scope_path, seg_text in split_into_scopes(text):
        seg_begin = len(results)
        seg_text = strip_wiki_markup(seg_text)
        desugared, spans = desugar(seg_text)
        sentences = SENTENCE_SPLIT_RE.split(desugared)

        for sent_idx, sent in enumerate(sentences):
          for clause in split_clauses(sent):
            sent_matches = []
            # Verbless declarations only fire in a declaration context
            # (Given / To prove / Suppose / "the following are equivalent
            # for ..."), where "a <descriptor> SYM(x)" really is
            # introducing x rather than just mentioning it in passing.
            active = list(patterns)
            if (DECLARATION_CONTEXT_RE.match(sent.strip())
                    or EXISTENTIAL_RE.search(sent)):
                active = active + VERBLESS_PATTERNS
            for pat in active:
                # Patterns are written with a literal "SYM(" for readability;
                # turn that into the escaped "SYM\(" the regex engine needs.
                working = pat["regex"].replace("SYM(", r"SYM\(")
                # finditer (not search): a single clause can still carry
                # more than one pattern match (e.g. bare is-a + is-a-of
                # both matching overlapping text) - collect all, dedup below.
                for m in re.finditer(working, clause, flags=re.IGNORECASE):
                    gd = m.groupdict()

                    # Object-position guard: if the matched subject symbol is
                    # immediately preceded by a preposition ("...of nonzero
                    # elements of SYM(L) is the center of..."), it is the
                    # object of that preposition, not the sentence's subject.
                    # Attributing the predicate to it produces a confidently
                    # wrong declaration ("L is the center of K^*" when the
                    # text says L^* is). Patterns that anchor on a head noun
                    # (subj_role) locate the subject correctly and are exempt.
                    if "subj_role" not in gd:
                        preceding = clause[:m.start()].rstrip()
                        if re.search(r"\b(?:" + _REL_PREP_ALT + r")\s*$", preceding, re.IGNORECASE):
                            continue

                    sym = normalize_symbol(gd.get("sym", ""))
                    role = (gd.get("role") or "").strip()
                    rel = normalize_symbol(gd.get("rel", "")) if gd.get("rel") else None
                    prep = (gd.get("prep") or "of").strip()
                    meaning = pat["template"].format(sym=sym, role=role, rel=rel, prep=prep)

                    # "of A with B" (e.g. "wreath product of the group of
                    # prime order with W") is a two-argument construction,
                    # NOT the "prep a <descriptor> X" idiom this pattern is
                    # meant for (e.g. "subgroup of a finite group G"). If
                    # the captured rel_role swallowed a trailing connector
                    # word (with/and/by/...), that descriptor is unreliable
                    # - but the primary fact "sym relates to rel" (role and
                    # rel come from separate, unaffected capture groups) is
                    # still fine and worth keeping at reduced confidence:
                    # dropping it entirely would make W (the referent)
                    # invisible to UNDECLARED_REFERENT rather than correctly
                    # flagged as "referenced but never itself declared".
                    descriptor_unreliable = pat.get("also_declares_rel") and _SECOND_ARG_RE.search(gd.get("rel_role") or "")
                    if descriptor_unreliable:
                        confidence = "low"
                    else:
                        confidence = pat.get("confidence", "high")

                    # Attachment ambiguity: the subject symbol is separated
                    # from its verb by prepositional phrases that themselves
                    # contain symbols ("the multiplicative group L^* OF
                    # nonzero elements OF L is the center of K^*"). We now
                    # resolve this correctly, but a reader skimming the
                    # sentence can misattach it the same way the parser
                    # originally did - so surface it as an advisory to add
                    # commas or parentheses. This is a readability warning,
                    # not a correctness error: the meaning below is right.
                    #
                    # If the author HAS set the modifier off with commas or
                    # parentheses, the subject is already unmistakable to a
                    # reader and the advisory is suppressed - otherwise the
                    # tool would keep nagging about a sentence that has
                    # already been fixed as it asked.
                    mid_text = gd.get("mid") or ""
                    # Strip SYM(...) placeholders before testing for author
                    # punctuation - the placeholders carry their own
                    # parentheses, which would otherwise look like the
                    # commas/parens we are asking the author to add.
                    mid_bare = re.sub(r"SYM\([^)]*\)", " ", mid_text)
                    already_punctuated = bool(re.search(r"[,()]", mid_bare))
                    ambiguous = bool(
                        pat.get("also_declares_subj_role")
                        and re.search(r"SYM\(", mid_text)
                        and not already_punctuated
                    )

                    sent_matches.append({
                        "sym": sym,
                        "role": role,
                        "rel": rel,
                        "meaning": meaning,
                        "sentence": sent.strip(),
                        "confidence": confidence,
                        "scope": scope_path,
                        "pos": desugared.find(sent[:40]) if sent else 0,
                        "kind": classify_declaration_kind(sent, clause),
                        "is_restatement": bool(RESTATEMENT_MARKERS_RE.match(sent.strip())),
                        "is_goal": bool(GOAL_CONTEXT_RE.match(sent.strip())
                                        or EXISTENTIAL_RE.search(sent)),
                        # For a restatement, record the nearest preceding
                        # sentence that mentions this symbol. We often can't
                        # PARSE that antecedent into a meaning (it may
                        # characterize the symbol implicitly, e.g. by placing
                        # it in a chain "H < K < G"), but we can point at it
                        # so a reviewer can compare the two by hand. Without
                        # this, a restatement whose antecedent is implicit
                        # looks like a lone characterization and is never
                        # surfaced for review.
                        "antecedent": _find_antecedent(sentences, sent_idx, sym),
                        "ambiguous_attachment": ambiguous,
                        "span": (m.start(), m.end()),
                    })
                    # Some patterns (e.g. "...of a finite group G") declare
                    # BOTH symbols in one match: the primary sym, and the
                    # relation target via its own inline descriptor. Emit a
                    # second declaration for the latter, anchored to the
                    # same span so dedup treats it as part of the same
                    # match - but only when the descriptor itself is
                    # trustworthy (see descriptor_unreliable above).
                    if pat.get("also_declares_subj_role") and gd.get("subj_role"):
                        subj_role = gd["subj_role"].strip()
                        sent_matches.append({
                            "sym": sym,
                            "role": subj_role,
                            "rel": None,
                            "meaning": f"{sym} is a {subj_role}",
                            "sentence": sent.strip(),
                            "confidence": pat.get("confidence", "high"),
                            "scope": scope_path,
                            "kind": "binding",
                            # Derived from apposition ("the group of prime
                            # order p"), which is a weaker inference than an
                            # explicit binding: the descriptor may actually
                            # qualify the symbol ("order p") rather than
                            # name it. If this conflicts with an existing
                            # binding, that's more likely a reading
                            # ambiguity than a real rebinding.
                            "from_apposition": True,
                            "span": (m.start(), m.end()),
                        })

                    if pat.get("also_declares_rel") and gd.get("rel_role") and not descriptor_unreliable:
                        rel_role = gd["rel_role"].strip()
                        sent_matches.append({
                            "sym": rel,
                            "role": rel_role,
                            "rel": None,
                            "meaning": f"{rel} is a {rel_role}",
                            "sentence": sent.strip(),
                            "confidence": pat.get("confidence", "high"),
                            "scope": scope_path,
                            # An inline descriptor ("...of a finite group G")
                            # introduces G, so it counts as a binding - but
                            # it's an apposition, so the descriptor may be
                            # qualifying the symbol ("the group of prime
                            # order p") rather than naming it. Conflicts get
                            # reported as ambiguity, not redefinition.
                            "kind": "binding",
                            "from_apposition": True,
                            "span": (m.start(), m.end()),
                        })

            # Dedup within this clause: when two matches overlap and share
            # the same symbol, keep only the wider (more specific) one,
            # e.g. "is-a-of" over bare "is-a" for the same span, since the
            # narrower one is almost always a partial submatch of the same
            # underlying declaration, not a second distinct one.
            sent_matches.sort(key=lambda r: -(r["span"][1] - r["span"][0]))
            kept = []
            for r in sent_matches:
                s0, e0 = r["span"]
                overlaps_kept_wider = any(
                    r["sym"] == k["sym"] and not (e0 <= k["span"][0] or s0 >= k["span"][1])
                    for k in kept
                )
                if not overlaps_kept_wider:
                    kept.append(r)
            for r in kept:
                del r["span"]
            results.extend(kept)

        # Second pass: definitional equations living entirely inside one
        # math span, e.g. "B = \mathbb{F}_p[H]" - these have no surrounding
        # English for the sentence-level patterns to anchor on.
        #
        # An equation in a CONCLUSION sentence ("thus d = 1", "we conclude
        # K = L") is a derived result, not a definition: treating it as one
        # makes a proof's own conclusion look like a redefinition of the
        # symbol it constrains. We locate each span's enclosing sentence to
        # decide. Likewise a bare-numeral RHS ("d = 1") is essentially never
        # a definition in running proof text.
        for content in spans:
            enclosing = ""
            marker = f"SYM({content.strip()})"
            for s in sentences:
                if marker in s:
                    enclosing = s
                    break

            if CONCLUSION_MARKERS_RE.search(enclosing):
                continue

            for pat in (equation_patterns or EQUATION_PATTERNS):
                m = re.match(pat["regex"], content.strip())
                if not m:
                    continue
                gd = m.groupdict()
                sym = normalize_symbol(gd.get("sym", ""))
                rhs = (gd.get("rhs") or "").strip()
                if re.fullmatch(r"-?\d+", rhs):
                    break  # "d = 1" - a constraint/result, not a definition
                meaning = pat["template"].format(sym=sym, role="", rel=None, rhs=rhs)
                results.append({
                    "sym": sym,
                    "role": "",
                    "rel": None,
                    "meaning": meaning,
                    "sentence": enclosing.strip() or f"${content.strip()}$",
                    "confidence": pat.get("confidence", "medium"),
                    "scope": scope_path,
                    "pos": desugared.find(marker),
                    "kind": classify_declaration_kind(enclosing or ""),
                    "is_restatement": bool(
                        RESTATEMENT_MARKERS_RE.match((enclosing or "").strip())),
                })
                break

        # Equations are collected in a second pass over the segment, so
        # without re-sorting they always appear after every prose sentence
        # regardless of where they actually occur. That inverts the order of
        # a definition and a later derived property, and REDEFINITION
        # compares against the most recent PRIOR meaning - so the inversion
        # manufactures conflicts that the text does not contain.
        results[seg_begin:] = sorted(results[seg_begin:],
                                     key=lambda r: r.get("pos", 0))

    return results


# --------------------------------------------------------------------------
# 4. Draft table generation (extract mode)
# --------------------------------------------------------------------------

def build_draft_table(declarations):
    """Group by symbol; a symbol may have multiple declarations if reused
    (that's exactly what we want the human to review). Each entry keeps
    its scope path so re-use across independent sections (e.g. two
    sibling ===Example=== subsections) doesn't get treated the same as
    re-use within one section."""
    table = {}
    for d in declarations:
        table.setdefault(d["sym"], []).append({
            "meaning": d["meaning"],
            "confidence": d["confidence"],
            "source_sentence": d["sentence"],
            "scope": list(d["scope"]),
            "kind": d.get("kind", "binding"),
        })
    return table


def write_table(table, path):
    if path.endswith((".yml", ".yaml")) and HAVE_YAML:
        Path(path).write_text(yaml.dump(table, sort_keys=True, allow_unicode=True))
    else:
        Path(path).write_text(json.dumps(table, indent=2, ensure_ascii=False))


def read_table(path):
    text = Path(path).read_text()
    if path.endswith((".yml", ".yaml")) and HAVE_YAML:
        return yaml.safe_load(text) or {}
    return json.loads(text)


# --------------------------------------------------------------------------
# 5. Consistency checking (check mode)
# --------------------------------------------------------------------------

def similar(a, b, threshold=0.82):
    return difflib.SequenceMatcher(None, a.lower(), b.lower()).ratio() >= threshold


GIVEN_COMPONENT_RE = re.compile(
    r"(?:an?|the)\s+(?P<role>[\w -]+?)\s+SYM\((?P<sym>[^)]+)\)"
    r"(?:\s+(?:of|with|having)\s+(?P<qualifier>[\w -]+?))?(?=\s*[,.;:]|$)",
    re.IGNORECASE,
)

# Words carrying no distinguishing content, so useless as a citation key.
_STOPWORDS = {"a", "an", "the", "of", "with", "size", "group", "set", "element"}


def given_components(given_text):
    """Split a Given block into its independent hypotheses.

    "A division ring K of finite size" is a CONJUNCTION: K is a division
    ring, and K is finite. Both are load-bearing and are typically consumed
    at different steps. Treating the Given as atomic makes partial citation
    invisible - the column looks used because the other component was cited.

    Returns [(symbol, description, keyword)] where keyword is the
    distinguishing word to look for in a 'Given data used' cell.
    """
    desugared, _ = desugar(strip_wiki_markup(given_text))
    out = []
    for m in GIVEN_COMPONENT_RE.finditer(desugared):
        sym = normalize_symbol(m.group("sym"))
        role = (m.group("role") or "").strip()
        qual = (m.group("qualifier") or "").strip()

        if role:
            key = [w for w in role.lower().split() if w not in _STOPWORDS]
            if key:
                out.append((sym, f"{sym} is a {role}", key[-1]))
        if qual:
            key = [w for w in qual.lower().split() if w not in _STOPWORDS]
            if key:
                out.append((sym, f"{sym} is {qual}", key[0]))
    return out


# Objects that force the construction to be infinite. If a page's
# constructions live over these, no finite instantiation exists, and tools
# that compute orders or emit GAP are structurally inapplicable - not merely
# short of data. Saying so is more useful than emitting a scaffold that can
# never run or an order arithmetic over quantities that are all infinite.
INFINITE_MARKERS = [
    (r"\\R\b|\\mathbb\{R\}", "the reals"),
    (r"\\mathbb\{Q\}", "the rationals"),
    (r"\\mathbb\{C\}", "the complex numbers"),
    (r"\bpositive reals\b", "the positive reals"),
    # Deliberately NOT included: "finitary" and a bare "infinite". Both
    # appear in pages that DO have finite instantiations - the
    # potentially-characteristic page mentions the finitary alternating
    # group only as a recipe for the infinite case, while its own smallest
    # example has order 14400. Only objects that are inherently infinite
    # count here.
]


def find_infinite_domain(text):
    """Report markers that the page's constructions are inherently infinite.

    Returns list of (severity, line_no, message). Advisory: it does not
    mean the page is wrong, it means finite computational verification is
    not available for it.
    """
    hits = []
    for pat, what in INFINITE_MARKERS:
        m = re.search(pat, text)
        if m:
            line = text.count("\n", 0, m.start()) + 1
            hits.append((what, line))
    if not hits:
        return []
    what = ", ".join(sorted({w for w, _ in hits}))
    line = min(l for _, l in hits)
    return [("INFINITE_DOMAIN", line,
             f"constructions on this page involve {what}; no finite "
             f"instantiation exists, so order arithmetic and GAP scaffolds "
             f"are structurally inapplicable rather than merely incomplete")]


def find_uncited_givens(text):
    """Advisory: a section states a Given, contains a tabular proof with a
    'Given data used' column, and no row cites anything in that column.

    The tabular format makes a structural commitment ordinary prose does
    not: the column exists to record where a hypothesis is consumed, so an
    empty cell asserts the step does not depend on it. An entirely empty
    column means the point where the Given first enters the argument was
    never recorded.

    Deliberately whole-table, not per-row. Downstream steps inherit a
    hypothesis through the 'Previous steps used' chain, so flagging every
    row that transitively depends on the Given would push toward redundant
    citations the step-reference chain already carries. What is missing is
    the single row where the Given is FIRST consumed.

    Returns list of (severity, line_no, message).
    """
    issues = []
    lines = text.split("\n")

    state = {
        "section": None, "given_seen": False, "given_text": [],
        "col_index": None, "n_rows": 0, "n_cited": 0,
        "cells_text": [], "table_line": 0,
    }

    def flush():
        st = state
        if not (st["given_seen"] and st["col_index"] is not None and st["n_rows"]):
            return
        if not st["n_cited"]:
            issues.append((
                "UNCITED_GIVEN", st["table_line"],
                f"section {st['section']!r} states a Given, but its "
                f"'Given data used' column is empty in all {st['n_rows']} rows - "
                f"the step where the hypothesis is first consumed is unrecorded"
            ))
            return

        # The column IS used, but a Given may be a CONJUNCTION of several
        # independent hypotheses ("a division ring K of finite size"), each
        # consumed at a different step. Check each component separately -
        # otherwise citing one makes the others look accounted for, and
        # dropping a citation becomes invisible.
        blob = " ".join(st["cells_text"]).lower()
        comps = given_components(" ".join(st["given_text"]))
        if len(comps) > 1:
            for sym, desc, key in comps:
                if key not in blob:
                    issues.append((
                        "UNCITED_GIVEN", st["table_line"],
                        f"section {st['section']!r}: the Given includes "
                        f"{desc!r}, but no row cites it in 'Given data used' "
                        f"(looked for {key!r}). Other parts of the Given ARE "
                        f"cited, so the column is in use - this component "
                        f"alone is unaccounted for"
                    ))

    for i, raw in enumerate(lines, 1):
        line = raw.strip()

        m = HEADER_RE.match(line)
        if m:
            flush()
            state.update({"section": m.group(2).strip(), "given_seen": False,
                          "given_text": [], "col_index": None,
                          "n_rows": 0, "n_cited": 0, "cells_text": []})
            continue

        if re.search(r"'''\s*Given\s*'''", line) or re.match(r"^Given\s*:", line, re.I):
            state["given_seen"] = True
            state["given_text"].append(line)

        if line.startswith("!"):
            headers = [h.strip().lstrip("!").strip()
                       for h in re.split(r"\s*!!\s*", line.lstrip("!"))]
            for idx, h in enumerate(headers):
                if re.search(r"given\s+data", h, re.IGNORECASE):
                    state["col_index"] = idx
                    state["table_line"] = i
            state["n_rows"] = state["n_cited"] = 0
            state["cells_text"] = []
            continue

        if line.startswith("|") and not line.startswith("|-") and not line.startswith("|}"):
            if state["col_index"] is None:
                continue
            cells = re.split(r"\s*\|\|\s*", line.lstrip("|"))
            state["n_rows"] += 1
            ci = state["col_index"]
            if ci < len(cells) and cells[ci].strip():
                state["n_cited"] += 1
                state["cells_text"].append(cells[ci])

    flush()
    return issues


def find_multiple_characterizations(declarations):
    """Group symbols that are characterized more than one way within a
    scope, so a reviewer (human or LLM) can confirm the characterizations
    actually agree.

    This is NOT an error check. Describing one object several ways is
    normal and often good writing. The failure mode it targets is the
    *underdetermined* restatement: a second description that picks out a
    different object than the first because a qualifying clause was
    dropped. Such a sentence is grammatically fine, introduces no new
    symbol, and conflicts with nothing - so every other check here passes
    it. Only a reader who knows the mathematics can settle it, which is
    exactly why it's surfaced as a prompt rather than a verdict.

    Returns a list of dicts, highest-priority first:
        {sym, scope, priority, characterizations: [{meaning, sentence,
         kind, is_restatement}]}

    priority is "high" when the characterizations are explicitly linked -
    same sentence, or one flagged by a restatement marker ("in other
    words", "equivalently"). Those are asserted to be equivalent, so a
    mismatch is a real defect rather than two independent true facts.
    Everything else is "normal": likely just accumulated properties.
    """
    groups = {}
    for d in declarations:
        groups.setdefault((d["sym"], d["scope"]), []).append(d)

    out = []
    for (sym, scope), decls in groups.items():
        # Collapse near-identical wordings; they aren't two characterizations.
        distinct = []
        for d in decls:
            if not any(similar(d["meaning"], k["meaning"]) for k in distinct):
                distinct.append(d)
        # A restatement whose antecedent couldn't be parsed into a meaning
        # still deserves review: show the raw antecedent sentence alongside
        # it. This is the case where the first characterization is implicit
        # (a symbol placed in a chain, say) rather than a parseable "X is a Y".
        antecedents = [d for d in distinct
                       if d.get("is_restatement") and d.get("antecedent")]
        if len(distinct) < 2 and not antecedents:
            continue

        # "high" requires an explicit restatement marker. Same-sentence
        # co-occurrence is too weak on its own: one long explanatory
        # sentence can mention a symbol several ways incidentally
        # ("we don't even use that H is a subgroup of G ... H is a subset
        # of G ...") without asserting those are equivalent.
        linked = any(d.get("is_restatement") for d in distinct)
        if len(distinct) < 2:
            linked = True  # restatement with an unparsed antecedent
        out.append({
            "sym": sym,
            "scope": list(scope),
            "priority": "high" if linked else "normal",
            "characterizations": [
                {
                    "meaning": d["meaning"],
                    "sentence": d["sentence"],
                    "kind": d.get("kind", "binding"),
                    "is_restatement": bool(d.get("is_restatement")),
                }
                for d in distinct
            ],
            # Raw sentences a restatement is restating, where we could not
            # parse them into a meaning. Unparsed on purpose - the reviewer
            # compares them by eye.
            "antecedents": sorted({d["antecedent"] for d in antecedents}),
        })

    out.sort(key=lambda g: (g["priority"] != "high", g["sym"]))
    return out


def format_characterizations(groups, indent=""):
    """Human-readable rendering of find_multiple_characterizations()."""
    lines = []
    for g in groups:
        tag = "VERIFY-EQUIVALENCE" if g["priority"] == "high" else "characterizations"
        n = len(g["characterizations"]) + len(g.get("antecedents", []))
        lines.append(f"{indent}[{tag}] '{g['sym']}' "
                     f"[{scope_label(tuple(g['scope']))}] "
                     f"is characterized {n} ways:")
        for i, c in enumerate(g["characterizations"], 1):
            mark = " (restatement)" if c["is_restatement"] else ""
            lines.append(f"{indent}    {i}. {c['meaning']}{mark}")
            lines.append(f"{indent}       from: \"{c['sentence'][:100]}\"")
        for a in g.get("antecedents", []):
            lines.append(f"{indent}    ~. (restating, unparsed) \"{a[:100]}\"")
        if g["priority"] == "high":
            lines.append(f"{indent}    -> these are asserted to be equivalent; "
                         f"confirm they pick out the same object")
    return "\n".join(lines)


def dedupe_declarations(declarations):
    """Collapse declarations that are identical in (sym, meaning, scope).
    The same math span or sentence often recurs across table cells, and
    re-reporting each copy inflates both the draft table and the issue
    list without adding information. Keeps first occurrence order."""
    seen = set()
    out = []
    for d in declarations:
        key = (d["sym"], d["meaning"], d["scope"])
        if key in seen:
            continue
        seen.add(key)
        out.append(d)
    return out


def check_consistency(declarations, approved_table):
    """Return list of (severity, message) tuples.

    Scope-aware: a symbol re-used with a different meaning is only flagged
    as REDEFINITION if the two declarations occur in *related* scopes
    (same section or table row, or one nested inside the other). Sibling
    scopes - two independent '===Example...===' subsections, or two steps
    of a tabular proof - are NOT compared against each other, since reuse
    there is normal, not a slip.

    Kind-aware: only 'binding' declarations ("Let L be the center of K")
    are compared for REDEFINITION. 'assertion' declarations ("L is a
    field", "L is an additive subgroup of K") state properties that are
    simultaneously true, so they accumulate rather than conflict.

    Each declaration is compared against the MOST RECENT related binding
    only, not every prior one - pairwise comparison turns n declarations
    of one symbol into O(n^2) messages saying substantially the same thing.
    """
    declarations = dedupe_declarations(declarations)

    issues = []
    last_meaning = {}  # sym -> (scope, meaning) of most recent declaration of any kind
    declared_syms = []  # list of (scope, sym) for every symbol declared so far, in order
    reported_undeclared = set()

    # Symbols declared together in the same sentence (e.g. "N is a subgroup
    # of a group M" declares N and M in one match) count as simultaneous,
    # not sequential - without this, whichever of the pair happens to be
    # processed first would wrongly see the other as "not yet declared".
    same_sentence_syms = {}
    for d in declarations:
        key = (d["scope"], d["sentence"])
        same_sentence_syms.setdefault(key, set()).add(d["sym"])

    for d in declarations:
        sym, meaning, scope = d["sym"], d["meaning"], d["scope"]

        # UNDECLARED_REFERENT: this declaration explains sym in terms of
        # another symbol ("B is a subgroup of C"), but that other symbol
        # has never itself been declared anywhere in a related scope -
        # it's only ever appeared as someone else's "of X" target, never
        # as a subject in its own right. Checked against declarations seen
        # so far (textual order) PLUS anything declared in this same
        # sentence (simultaneous declarations, see same_sentence_syms above).
        if d.get("rel") and d["rel"] != sym:
            rel_declared = any(
                s == d["rel"] and scope_visible_from(rscope, scope)
                for rscope, s in declared_syms
            )
            if not rel_declared:
                rel_declared = d["rel"] in same_sentence_syms.get((scope, d["sentence"]), set())
            if not rel_declared and d["rel"] not in reported_undeclared:
                # Report each never-declared symbol ONCE. A symbol used
                # throughout a survey page produces one finding, not one per
                # use: fourteen copies of "G is never declared" is a single
                # fact rendered unreadable.
                reported_undeclared.add(d["rel"])
                uses = sum(1 for x in declarations if x.get("rel") == d["rel"])
                extra = (f" (used this way {uses} times on the page)"
                         if uses > 1 else "")
                issues.append((
                    "UNDECLARED_REFERENT",
                    f"'{d['rel']}' is used to describe '{sym}' (\"{meaning}\") "
                    f"[{scope_label(scope)}] but '{d['rel']}' itself is never "
                    f"declared{extra} -- (\"{d['sentence'][:70]}\")",
                ))

        # AMBIGUOUS_ATTACHMENT (advisory): the declaration was resolved
        # correctly, but the sentence separates its subject from its verb
        # with prepositional phrases containing other symbols. A reader can
        # misattach the predicate to the nearer symbol just as a naive
        # parser does. Suggest punctuation; the meaning itself is fine.
        if d.get("ambiguous_attachment"):
            issues.append((
                "AMBIGUOUS_ATTACHMENT",
                f"'{sym}' is separated from its verb by phrases containing other "
                f"symbols; read as \"{meaning}\" [{scope_label(scope)}]. Consider "
                f"commas or parentheses to make the subject unmistakable "
                f"-- (\"{d['sentence'][:70]}\")",
            ))

        # SELF_REFERENCE: symbol declared in terms of itself, e.g.
        # "A is a subgroup of A". Always worth a human look regardless
        # of scope - this is a deterministic, high-confidence catch.
        if d.get("rel") and d["rel"] == sym:
            issues.append((
                "SELF_REFERENCE",
                f"'{sym}' is declared in terms of itself: \"{meaning}\" "
                f"[{scope_label(scope)}] -- (\"{d['sentence'][:70]}\")",
            ))

        # REDEFINITION: fires when a symbol is re-BOUND to a meaningfully
        # different meaning within a related scope. The *current*
        # declaration must be a binding (property assertions accumulate and
        # never conflict), but it is compared against the most recent prior
        # meaning of either kind - re-binding a symbol that already had an
        # established meaning is exactly the error worth catching, whether
        # that meaning came from an earlier binding or an assertion.
        if d.get("kind", "binding") == "binding":
            prior = last_meaning.get(sym)
            if prior is not None:
                prior_scope, prior_meaning = prior
                if scopes_related(prior_scope, scope) and not similar(prior_meaning, meaning):
                    if d.get("from_apposition"):
                        # The conflicting reading came from apposition ("the
                        # group of prime order p"), where the descriptor may
                        # be qualifying the symbol rather than naming it.
                        # Report the ambiguity, not a redefinition - but do
                        # report it, since a reader can misread it too.
                        issues.append((
                            "AMBIGUOUS_ATTACHMENT",
                            f"'{sym}' already means \"{prior_meaning}\", but the phrasing "
                            f"here also reads as \"{meaning}\" [{scope_label(scope)}]. "
                            f"Likely the descriptor qualifies '{sym}' rather than naming "
                            f"it; consider rewording -- (\"{d['sentence'][:70]}\")",
                        ))
                    else:
                        issues.append((
                            "REDEFINITION",
                            f"'{sym}' previously meant \"{prior_meaning}\" "
                            f"[{scope_label(prior_scope)}], now re-bound as \"{meaning}\" "
                            f"[{scope_label(scope)}] -- (\"{d['sentence'][:70]}\")",
                        ))
        # A goal or existential ("To prove: there exists a group K ...")
        # names a witness rather than fixing a meaning, so it must not
        # become the baseline a later construction is compared against -
        # otherwise every proof that builds its witness looks like a
        # redefinition of the thing it was asked to produce.
        if not d.get("is_goal"):
            last_meaning[sym] = (scope, meaning)

        # DRIFT: not present in the human-approved table at all, or present
        # only under an unrelated scope.
        approved = approved_table.get(sym)
        if approved is None:
            issues.append((
                "DRIFT",
                f"'{sym}' declared as \"{meaning}\" [{scope_label(scope)}] "
                f"but not in approved table -- (\"{d['sentence'][:70]}\")",
            ))
        else:
            relevant = [
                a for a in approved
                if scopes_related(tuple(a.get("scope", [])), scope)
            ]
            candidates = relevant or approved  # fall back to all if scope info missing/unrelated
            approved_meanings = [a["meaning"] for a in candidates]
            if not any(similar(meaning, am) for am in approved_meanings):
                issues.append((
                    "DRIFT",
                    f"'{sym}' now means \"{meaning}\" [{scope_label(scope)}] but "
                    f"approved table (same-scope entries) says {approved_meanings} "
                    f"-- (\"{d['sentence'][:70]}\")",
                ))

        declared_syms.append((scope, sym))

    # POSSIBLE_ALIAS (soft): different symbols, near-identical meaning text,
    # restricted to related scopes - otherwise every page-wide reuse of
    # "is a subgroup of" phrasing floods the output with noise.
    #
    # Ultra-generic roles are excluded: on a group theory page most symbols
    # are "a group" or "a subgroup", so matching on those says nothing about
    # whether two symbols are actually the same object.
    GENERIC_ROLES = {
        "group", "subgroup", "set", "element", "field", "ring", "space",
        "map", "function", "number", "integer", "prime",
    }
    items = [(d["sym"], d["meaning"], d["scope"], (d.get("role") or "").strip().lower())
             for d in declarations]
    for i in range(len(items)):
        for j in range(i + 1, len(items)):
            sym_a, mean_a, scope_a, role_a = items[i]
            sym_b, mean_b, scope_b, role_b = items[j]
            if role_a in GENERIC_ROLES and role_b in GENERIC_ROLES:
                continue
            if (sym_a != sym_b
                    and scopes_related(scope_a, scope_b)
                    and similar(mean_a, mean_b, threshold=0.9)):
                # Show BOTH meanings. Printing only one hides the case that
                # matters most: two descriptions that are nearly identical
                # but differ in one token (T_1 vs T_2) - exactly where a
                # copy-paste slip would live. Identical text and a one-token
                # difference need different responses from the reader.
                if mean_a == mean_b:
                    detail = f"both mean \"{mean_a}\""
                else:
                    detail = (f"mean nearly the same thing:\n"
                              f"        {sym_a}: {mean_a}\n"
                              f"        {sym_b}: {mean_b}")
                issues.append((
                    "POSSIBLE_ALIAS",
                    f"'{sym_a}' [{scope_label(scope_a)}] and '{sym_b}' "
                    f"[{scope_label(scope_b)}] {detail} -- "
                    f"confirm this is intentional (e.g. two distinct subgroups)",
                ))

    return issues


# --------------------------------------------------------------------------
# 6. CLI
# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_extract = sub.add_parser("extract", help="Draft a symbol->meaning table from a page")
    p_extract.add_argument("file")
    p_extract.add_argument("--out", required=True, help="Output path for draft table (.json or .yaml)")
    p_extract.add_argument("--patterns-file", default=None)

    p_check = sub.add_parser("check", help="Check a page against a human-approved table")
    p_check.add_argument("file")
    p_check.add_argument("--approved", required=True, help="Path to human-approved table")
    p_check.add_argument("--patterns-file", default=None)

    args = ap.parse_args()
    patterns = load_patterns(args.patterns_file)
    text = Path(args.file).read_text()
    declarations = extract_declarations(text, patterns)

    if args.cmd == "extract":
        for sev, line_no, msg in find_malformed_math_tags(text):
            loc = f"line {line_no}" if line_no else "file"
            print(f"[{sev}] {loc}: {msg}")
        declarations = dedupe_declarations(declarations)
        table = build_draft_table(declarations)
        write_table(table, args.out)
        print(f"Extracted {len(declarations)} declarations, {len(table)} distinct symbols.")
        print(f"Draft table written to {args.out} -- please review before using as 'approved'.")

    elif args.cmd == "check":
        approved = read_table(args.approved)
        issues = [
            (sev, (f"line {ln}: " if ln else "") + msg)
            for sev, ln, msg in find_malformed_math_tags(text)
        ]
        issues += check_consistency(declarations, approved)
        if not issues:
            print("Clean: no redefinitions, drift, or possible aliases detected.")
        for severity, msg in issues:
            print(f"[{severity}] {msg}")
        print(f"\n--- summary: {len(issues)} issue(s) across {len(declarations)} declaration(s) ---")


if __name__ == "__main__":
    main()
